version: "3.6"

services:
  arangodb:
    image: arangodb/arangodb
    ports:
      - "8529:8529"
    volumes:
      - data_arangors:/var/lib/arangodb3
    environment:
      - ARANGO_STORAGE_ENGINE=rocksdb
      - ARANGO_ROOT_PASSWORD=KWNngteTps7XjrNv
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  data_arangors:
    driver: local
